### PR TITLE
fix(download): use user-agent 'firmware-updater'

### LINKED ISSUE #178: Cannot download releases
https://fwupd.org/downloads now returns 429 when we try to download a *.cab file with dio:
```
Access denied -- you must set the User-Agent header to use this endpoint
```

### PR DESCRIPTION
**Pull request by d-loose**
I'm open to suggestions for a more detailed user-agent string :)

Close #178

### CODE REVIEW

File: lib/fwupd_service.dart [hunk 1]
```diff
@@ -111,9 +111,14 @@ class FwupdService {
...
-      return await _dio.download(url, path, onReceiveProgress: (recvd, total) {
-        _setDownloadProgress(100 * recvd ~/ total);
-      }).then((response) => _fs.file(path));
+      return await _dio.download(
+        url,
+        path,
+        onReceiveProgress: (recvd, total) {
+          _setDownloadProgress(100 * recvd ~/ total);
+        },
+        options: Options(headers: {'User-Agent': 'firmware-updater'}),
```
Comment (jpnurmi) [inline lib/fwupd_service.dart:120]: i saw `HttpHeaders.userAgentHeader` being used in dio examples but this is fine too :)

**Review by jpnurmi — APPROVED** [review]
i don't know what's the best practice but in some dart libraries of ours, we default to "foo.dart" so this is in line with that :+1:
